
#print "error"
#halt

// This isn't really a bug, but just something that should work

struct Dummy ()

func main {
    getDummy().getDummy().getDummy()
}

func getDummy Dummy {
    d POD Dummy = undef
    return d
}
